name: Lint

on:
  push:

jobs:
  check-black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: ./.github/actions/lint-install
      - name: Run black
        run: |
          make check-black

  check-isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: ./.github/actions/lint-install
      - name: Run isort
        run: |
          make check-isort

  check-mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: ./.github/actions/lint-install
      - name: Run mypy
        run: |
          make check-mypy

  check-flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: ./.github/actions/lint-install
      - name: Run flake8
        run: |
          make check-flake8

  check-pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run pylint
        run: |
          make install-dev
          make check-pylint
